dist: trusty
language: python
addons:
  sonarcloud:
    organization: "borisv13-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN2 # encrypted value of your token
python:
  - "3.6"

install:
  - pip install -r requirements.txt
script:
  - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
# - py.test  --cov-report term --cov=.
  - py.test  --cov-report term --cov=./backend/
  - coverage xml
services:
  - sqlite
env:
  - DJANGO=2.2.6
after_success:
  - codecov
